// <auto-generated />
namespace SXC.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zs34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zs34));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281317151_zs3.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
