// <auto-generated />
namespace SXC.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zs25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zs25));
        
        string IMigrationMetadata.Id
        {
            get { return "201709280505463_zs2.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
